### ISSUE TITLE
How to deal with 16bit data?

### ISSUE THREAD

**Issue by ver228** [ver228/Multiworm_Tracking#2]
The new camera produces 12bit data. For the moment all the code requires and produces images with 8bit. How should we deal with this? 
**Option1:** Rescale 16bit images into 8bit images. It would be important to be able to redo the scaling in case one is interested in the absolute values of fluorescence. It should be possible to do this by adding an extra vector in the hdf5 that specifies how to the scaling was done for each frame. The risk is that some precision is lost due to rounding errors. 
When I say scaling it could be either:
* *Normalization:* pixel_intensity - max intensity / (max_intensity-min_intensity + 1) * 255)
*  *Bit shift*: keep only the higher significative bit (e.g. 677 = 1010100101 will be encoded as 169 = 10101001, plus a left_shift 2).

**Option2:** Enable to support other datatypes (uint16, maybe float32). The problem is that it would require a lot of testing since I am not sure until what level the uint8 datatype is important. The code in the repository can be modified but I think some methods of OpenCV only work with uint8 (maybe float32). My concern is that it might require a few wrappers that convert data back to uint8 making the first option preferable. Other option is the size of the videos. Even after compression uint16/float32 would be significatively larger than uint8.

**Comment by ljschumacher** [comment]
I agree Option 1 would be preferable. From my own testing I think the OpenCV thresholding requires 8 bit.

**Comment by ver228** [comment]
Yes, and probably the normalization is better. However, it does worry me the lost of precision. If the dynamic range of the images is small it shouldn't be a problem, but I would not like to discover later that it was not enough and we need to modify all our code again. Maybe we should discuss it with Andre. He has been quite insistent into having lossless compression of the worm pixels.

In any case, I would modify the dat reader to return a 16bit image. Then we can add an extra code in compressWormVideo that will transform the image if the datatype is other than uint8  and save the normalization parameters (min and max intensities).

**Comment by ljschumacher** [comment]
I've added in the normalisation in the latest pull request, but have not had a chance to test it yet.

Note the typo in your first comment (it should be "pixel_intensity - max_intensity"...)
